config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :topics do
    resources :comments
    post :confirm ,on: :collection
  end

  devise_for :users,controllers:{
    registrations:"users/registrations",
    omniauth_callbacks:"users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]
  resources :relationships,only:[:create,:destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at:'/letter_opener'
  end

  authenticated :user do                                                 # Userがログイン中はtopic一覧をtop画面とする設定
    root :to => "topics#index", :as => "user_authenticated_root"
  end

  devise_scope :user do                                                  # User非ログイン中はサインアップ画面をtop画面とする設定
    root :to => "users/registrations#new"                                # RegistrationsControllerのnew.html.erbに飛ばしている
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates:content,presence:true,length:{maximum: 100}

  belongs_to :user
  belongs_to :topic
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment,only:[:edit,:update,:destroy]
  # コメントを保存、投稿するためのアクション
  def create
    # Topicをパラメータの値から探し出し,Topicに紐づくcommentsとしてbuildする
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to topic_path(@topic), notice: 'コメントを投稿しました。' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
      respond_to do |format|
        if @comment.update(comment_params)
          format.html {redirect_to topic_path(@comment.topic), notice:"コメントを編集しました！"}
        else
          format.html { render :edit }
        end
      end
  end

  def destroy
    respond_to do |format|
      if @comment.destroy
        format.js { render :index }  # JS形式でレスポンスを返す
      else
        format.html { render :new }
      end
    end
  end

  private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end
    def set_comment
      @comment = Comment.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment],remote: true) do |f| %>   <!-- remote: trueでAjyax使用 -->
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <br>
    <%= f.text_field :content, placeholder: "コメント入力", class: "form-control"  %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%=form_for(@comment, url: topic_comment_path) do |f| %>
      <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= @comment.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.hidden_field :topic_id %>
    <br>
    <br>
    <%= f.label :コメント内容 %><br />
    <br>
    <div class="field">
      <%= f.text_field :content,class: "form-control"  %>
    </div>
    <br>
      <%= f.submit "更新" %>
    <% end %>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')