config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :topics do
    resources :comments
    post :confirm ,on: :collection
  end

  devise_for :users,controllers:{
    registrations:"users/registrations",
    omniauth_callbacks:"users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]
  resources :relationships,only:[:create,:destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at:'/letter_opener'
  end

  authenticated :user do                                                 # Userがログイン中はtopic一覧をtop画面とする設定
    root :to => "topics#index", :as => "user_authenticated_root"
  end

  devise_scope :user do                                                  # User非ログイン中はサインアップ画面をtop画面とする設定
    root :to => "users/registrations#new"                                # RegistrationsControllerのnew.html.erbに飛ばしている
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates:content,presence:true,length:{maximum: 350}

  mount_uploader :topicimage,TopicUploader  # carrierwave用の設定(modelとアップローダーの紐付け)

  belongs_to :user
  has_many :comments,dependent: :destroy  #CommentモデルのAssociation設定

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!        #ログイン有無のチェック
  before_action :set_topic,only:[:show,:edit,:update,:destroy]

  def index
    @topics = Topic.all
  end

  def show
    @comment = @topic.comments.build   # 入力フォーム用インスタンス
    @comments = @topic.comments        # 一覧用インスタンス
  end

  def new
    if params[:back]
      @topic = Topic.new(topics_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topics_params)
    @topic.user_id = current_user.id      #contentと一緒にuser_idも保存されるようにする*/
    if params[:cache]
      @topic.topicimage.retrieve_from_cache! params[:cache][:topicimage]
    end
    if @topic.save
        redirect_to topics_path,notice:"投稿しました"
        NoticeMailer.sendmail_topic(@topic).deliver      #Mailer呼び出し
      else
        render'new'
      end
  end

  def edit

  end

  def update
    if @topic.update(topics_params)
      redirect_to topics_path,notice:"編集しました"
    else
      render'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path,notice:"削除しました"
  end

  def confirm
      @topic = Topic.new(topics_params)
      render :new if @topic.invalid?
  end

  private
  def topics_params
    # topicimageを保存する時に、確認画面で一時的にキャッシュしたものを掘り出して値にセットし、保存
    params.require(:topic).permit(:content,:topicimage,:topicimage_cache)
  end
    def set_topic
      @topic = Topic.find(params[:id])
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_topics_path
    elsif action_name == 'edit'
      topic_path
    end
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic,url:choose_new_or_edit) do |f| %>
  <% if @topic.errors.any? %>
    <div id = "error_explanation">
      <h2><%= @topic.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "field">
    <%= f.label :写真 %>      <!-- carrierwaveによる画像アップ -->
    <br>
    <br>
    <%= f.file_field :topicimage %>
    <%= f.hidden_field :topicimage_cache %>
  </div>
  <br>
  <br>
  <%= f.label :本文 %><br />
  <br>
  <%= f.text_field :content,class:'form-control' %>
  <br>
  <br>
  <br>
  <%= f.submit "投稿"%>
  <br>
  <br>
<% end %>
<br>
<br>
<%= link_to "一覧",topics_path %>
<br>
<br>

app/views/topics/confirm.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <br>
    <h5 style = "text-decoration:underline">確認</h5>
    <%= form_for(@topic)do |f| %>
      <%= hidden_field_tag :"cache[topicimage]",@topic.topicimage.cache_name %>
      <%= f.hidden_field :content %>
      <br>
      <%if @topic.topicimage? %>
        <%= image_tag(@topic.topicimage.url) %>
      <% end %>
      <br>
      <br>
      <p>本文<br /><%= @topic.content %></p>
      <br>
      <%= f.submit "送信",class:'btn btn-default btn-sm' %>
      <br>
      <br>
    <% end %>

    <%= form_for(@topic,url: new_topic_path,method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "戻る", name: 'back',class:'btn btn-default btn-sm' %>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <br>
    <br>
    <br>
    <%= render'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<div class = "container">
  <div class = "wrapper col-md-12 col-sm-10">
    <p id = "notice"><%= notice %></p>
    <h3>トピックス</h3>
    <% @topics.reverse_each do |topic| %>    <!-- reverse_eachとすることで新規投稿が上に掲載されるようにする -->
    <div class = "row">
      <br>
      <p><%= topic.content %></p>
      <br>
      <br>
      <div class = "topic">
        <%if topic.topicimage? %>
          <%= image_tag(topic.topicimage) %>
        <% end %>
    </div>
      <br>
      <!-- Topicにlink_toで詳細リンクを設定する -->
      <%= link_to topic_path(topic) do %>
        <h5><strong>詳細を見る</strong></h5>
      <% end %>
      <br>
      <div class = "contributor">
        <p>投稿者：<%= topic.user.name %><span style="margin-right: 5px;"></span><%= profile_img(@user = topic.user) %></p>
      </div>
      <br>
      <%= link_to "編集",edit_topic_path(topic.id),class:'btn btn-default btn-sm' %>
      <%= link_to "削除",topic_path(topic.id),method: :delete,data:{confirm:'本当に削除していいですか？'},class:'btn btn-default btn-sm' %>
    </div>
    <% end %>
  </div>
  <div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
  </div>
</div>

app/views/topics/new.html.erb
<div class = "container">
  <div class = "col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <br>
    <br>
    <br>
    <%= render'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<p id = "notice"><%= notice %></p>
<div class = "child row">
  <div class = "wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class = "topic-text">
      <p class = "left"><%= image_tag(@topic.topicimage) %><p>
      <p class = "left"><strong>本文</strong></p>
      <p class = "left"><%= @topic.content %></p>
      <p class = "right">
        <strong>作成時間：</strong>
        <%= @topic.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %>
      </p>
      <br>
      <% if current_user.id == @topic.user_id %>
        <%= link_to'編集　',edit_topic_path(@topic) %>
      <% end %>
      <%= link_to'戻る',topics_path %>
    </div>
    <br>
    <br>
    <p>コメント一覧</p>
    <div id = "comments_area">
      <%= render partial: 'comments/index',locals:{comments: @comments,topic: @topic} %>
    </div>
    <%= render partial: 'comments/form',locals:{comment: @comment,topic: @topic} %>
  </div>
</div>