config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :topics do
    resources :comments
    post :confirm ,on: :collection
  end

  devise_for :users,controllers:{
    registrations:"users/registrations",
    omniauth_callbacks:"users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]
  resources :relationships,only:[:create,:destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at:'/letter_opener'
  end

  authenticated :user do                                                 # Userがログイン中はtopic一覧をtop画面とする設定
    root :to => "topics#index", :as => "user_authenticated_root"
  end

  devise_scope :user do                                                  # User非ログイン中はサインアップ画面をtop画面とする設定
    root :to => "users/registrations#new"                                # RegistrationsControllerのnew.html.erbに飛ばしている
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ganmenbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">     <!-- mobile対応(スマホ&タブレット) -->
</head>
<body>
  <% if current_user %>   <!-- ユーザーがログイン中のみヘッダー表示 -->
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header"style=width:100%;">
          <%= link_to "Ganmenbook", root_path, class: "navbar-brand" %>
          <div class = "header-container"style=width:100%;">
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown"style="max-width: 100px;float: right;">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">menu<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "新規投稿", new_topic_path %></li>
                  <li><%= link_to "トピック", topics_path %></li>
                  <li><%= link_to "メッセージ", conversations_path %></li>
                  <% if user_signed_in? %>
                    <li><%= link_to 'ユーザー一覧', users_path %></li>
                    <li><%= link_to 'マイページ', edit_user_registration_path %></li>
                    <li><%= link_to'ログアウト',destroy_user_session_path,method: :delete %></li>
                  <% else %>
                    <li><%= link_to 'ログイン', new_user_session_path  %></li>
                    <li><%= link_to 'サインアップ', new_user_registration_path %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
  </header>
  <% end %>

  <%= yield %>

  <% if current_user %>   <!-- ユーザーがログイン中のみフッター表示 -->
  <footer>
    <p>運営会社　Ganmenbook株式会社</p>
    <p>© 2015-2016 Copyright Ganmenbook Corp.</p>
  </footer>
  <% end %>

</body>
</html>